#-- Completion --#
fpath=(~/.zsh/zsh-completions/src $fpath)
autoload -Uz compinit && compinit -C
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

#-- History --#
# ref: https://qiita.com/neriai/items/916307fc5f74cac6fbcd
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_no_store
setopt EXTENDED_HISTORY
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_verify
setopt hist_reduce_blanks
setopt hist_save_no_dups
setopt share_history
setopt hist_expand
setopt inc_append_history

#-- Alias --#
if [[ "$OSTYPE" == *darwin* ]]; then
  alias ls="ls -G"
elif [[ "$OSTYPE" == *linux* ]]; then
  alias ls="ls --color=auto"
fi
mkcd() {
  mkdir -p "$1" && cd "$1"
}

#-- Navigation --#
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups

#-- Key --#
bindkey -e
setopt correct

#-- Prompt --#
if (( $+commands[starship] )); then
  eval "$(starship init zsh)"
else
  # Git
  # ref: https://maimux2x.hatenablog.com/entry/2023/12/23/101355
  autoload -Uz vcs_info
  setopt prompt_subst
  zstyle ':vcs_info:git:*' check-for-changes true
  zstyle ':vcs_info:git:*' stagedstr "%F{magenta}!%f"
  zstyle ':vcs_info:git:*' unstagedstr "%F{yellow}+%f"
  zstyle ':vcs_info:*' formats "%c%u%F{cyan}[%b]%f"
  zstyle ':vcs_info:*' actionformats '%c%u%F{red}[%b|%a]%f'
  precmd () { vcs_info }

  PROMPT='
%(?.%F{green}.%F{red})╭─%f %B%F{blue}%n@%m%f%b: %F{cyan}%~%f $vcs_info_msg_0_
%(?.%F{green}.%F{red})╰─%f %# '
  RPROMPT="[%T]"
fi

#-- Package --#
[[ -f "$HOME/.fzf.zsh" ]] && source ~/.fzf.zsh
[[ -d "$HOME/.zsh/zsh-autosuggestions" ]] && source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
[[ -d "$HOME/.zsh/zsh-syntax-highlighting" ]] && source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#-- Path --#
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$HOME/.local/bin:$PATH"
